trigger:
  branches:
    include:
      - main  # Runs when the main branch is updated

pool:
  vmImage: 'ubuntu-latest'  # Use 'macOS-latest' for iOS



steps:

# ----------------------------------------
# STEP 1: Install Flutter SDK
# ----------------------------------------
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'custom'
    customVersion: '3.7.0'

# ----------------------------------------
# STEP 2: Verify Flutter & Install Dependencies
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter --version
    flutter pub get
  displayName: 'Setup Flutter'

# ----------------------------------------
# STEP 3: Build APK
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter build apk --release  # For Android
    # flutter build ios --release --no-codesign  # For iOS (uncomment if needed)
  displayName: 'Build Release App'

# ----------------------------------------
# STEP 4: Publish APK
# ----------------------------------------
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/app/outputs/flutter-apk/'
    Contents: '*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

