trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterVersion: 'stable'  # Use stable channel instead of master
  javaVersion: '11'

steps:
# ----------------------------------------
# STEP 1: System Dependencies
# ----------------------------------------
- script: |
    sudo apt-get update
    sudo apt-get install -y unzip libgtk-3-dev mesa-utils
  displayName: 'Install System Dependencies'

# ----------------------------------------
# STEP 2: Install Flutter from Stable Channel
# ----------------------------------------
- script: |
    git clone https://github.com/flutter/flutter.git -b $(flutterVersion) --depth 1
    echo "##vso[task.prependpath]$(pwd)/flutter/bin"
    echo "##vso[task.setvariable variable=FLUTTER_HOME]$(pwd)/flutter"
    
    # Accept Android licenses
    yes | sdkmanager --licenses
    flutter doctor --android-licenses
    
    flutter --version
  displayName: 'Install Flutter'

# ----------------------------------------
# STEP 3: Install Android SDK Components
# ----------------------------------------
- script: |
    echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"
  displayName: 'Install Android SDK'

# ----------------------------------------
# STEP 4: Setup Environment
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter pub cache repair
    flutter clean
    
    # Fix for missing analysis_defaults
    if [ -d "../analysis_defaults" ]; then
      echo "Local analysis_defaults package exists"
    else
      echo "Using default analysis settings"
      flutter pub get
    fi
  displayName: 'Prepare Environment'

# ----------------------------------------
# STEP 5: Build
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter build apk --release --verbose
  displayName: 'Build Release APK'