trigger:
  branches:
    include: ['main']  # Runs when main branch is updated

pool:
  vmImage: 'ubuntu-latest'  # Use 'macOS-latest' for iOS

variables:
  flutterVersion: '3.13.0'  # Specify Flutter version

steps:
# ----------------------------------------
# STEP 1: Install Flutter SDK
# ----------------------------------------
- script: |
    git clone https://github.com/flutter/flutter.git -b $(flutterVersion) --depth 1
    echo "##vso[task.setvariable variable=FLUTTER_HOME]$(pwd)/flutter"
  displayName: 'Install Flutter'

# ----------------------------------------
# STEP 2: Verify Flutter & Install Dependencies
# ----------------------------------------
- script: |
    export PATH="$(FLUTTER_HOME)/bin:$PATH"
    flutter --version
    flutter pub get
  displayName: 'Setup Flutter'

# ----------------------------------------
# STEP 3:Downgrade Java
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'     # <-- this is the correct key
    jdkSourceOption: 'PreInstalled'
  displayName: 'Use Java 11'
  # ----------------------------------------
  
# STEP 4: Build APK/IPA
# ----------------------------------------
- script: |
    export PATH="$(FLUTTER_HOME)/bin:$PATH"
    flutter build apk --release  # For Android
    # flutter build ios --release --no-codesign  # For iOS (uncomment if needed)
  displayName: 'Build Release App'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/app/outputs/flutter-apk/'
    Contents: '*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
# ----------------------------------------
