trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterChannel: 'master'

steps:
# ----------------------------------------
# STEP 1: Install Flutter (from master)
# ----------------------------------------
- script: |
    git clone https://github.com/flutter/flutter.git --branch ${{ variables.flutterChannel }} --depth 1
    echo "##vso[task.setvariable variable=FLUTTER_HOME]$(pwd)/flutter"
  displayName: 'Clone Flutter (master branch)'

# ----------------------------------------
# STEP 2: Setup Flutter & Install Dependencies
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter doctor
    flutter --version
    dart --version

    flutter pub get
  displayName: 'Setup Flutter and Fetch Dependencies'

# ----------------------------------------
# STEP 3: Build APK
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter build apk --release
  displayName: 'Build Release APK'

# ----------------------------------------
# STEP 4: Publish APK Artifact
# ----------------------------------------
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/app/outputs/flutter-apk/'
    Contents: '*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
