trigger:
  branches:
    include:
      - main  # Runs when main branch is updated

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterVersion: '3.19.6'

steps:
# ----------------------------------------
# STEP 1: Install Flutter SDK
# ----------------------------------------
- script: |
    git clone https://github.com/flutter/flutter.git -b ${{ variables.flutterVersion }} --depth 1
    echo "##vso[task.setvariable variable=FLUTTER_HOME]$(pwd)/flutter"
  displayName: 'Install Flutter'

# ----------------------------------------
# STEP 2: Setup Flutter & Install Dependencies
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter doctor
    flutter --version
    dart --version

    # Ensure pubspec.yaml allows Dart 3.3.0+ (required)
    sed -i 's/sdk: .*/sdk: ">=3.3.0 <4.0.0"/' pubspec.yaml

    flutter pub get
  displayName: 'Setup Flutter'

# ----------------------------------------
# STEP 3: Build APK
# ----------------------------------------
- script: |
    export PATH="$FLUTTER_HOME/bin:$PATH"
    flutter build apk --release
  displayName: 'Build Release APK'

# ----------------------------------------
# STEP 4: Publish APK
# ----------------------------------------
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/app/outputs/flutter-apk/'
    Contents: '*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
